networks:
  public:
    external:
      name: frontend
services:
  test:
    build:
      context: ./
      dockerfile: "published.Dockerfile"
    restart: always
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html
      - type: bind
        source: ./log
        target: /var/log/apache2
    environment:
      - TZ=Australia/Canberra
    networks:
      - public
