server:
  - endpoint_name: notebook_a
    path: notebook_a/
    metadata:
      - classname: title
      - classname: date
      - classname: tags
        group: li
  - endpoint_name: notebook_b
    path: notebook_b/
    metadata:
      - classname: title
      - classname: date
      - classname: tags
        group: li
