server:
  - endpoint_name: notebook_a
    path: notebook_a/notebook_a/
    media:
      - media/
    metadata:
      - classname: title
      - classname: date
      - classname: tags
        group: li
  - endpoint_name: notebook_b
    path: notebook_b/notebook_b/
    media:
      - media/
    metadata:
      - classname: title
      - classname: date
      - classname: tags
        group: li
